import "./globals.css";

export const metadata = {
  title: "Property Pulse",
  description: "Generated by create next app",
  keywords: "real estate, property, pulse, homes, apartments, houses, rent, buy, sell",
  authors: [{ name: "SUNGUR", url: "https://sungur.dev" }],
  creator: "SUNGUR",
  viewport: {
    width: "device-width",
    initialScale: 1,
  },
  icons: {
    icon: "/favicon.ico",
  },
};

export default function MainLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
